/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.Socket;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.SourceDataLine;
import javax.sound.sampled.TargetDataLine;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class FormCall extends javax.swing.JFrame implements Runnable{

    Socket s;
    DataOutputStream out;
    BufferedReader inp;
    Thread t;
    public int port_server = 8888;
    public String add_server = "localhost";
    public boolean calling = false;
    public AudioFormat getAudioFormat(){
        float sampleRate = 8000.0F;
        int sampleSizeInBits = 16;
        int channel = 2;
        boolean signed = true;
        boolean bigEndian = true;
        return new AudioFormat(sampleRate, sampleSizeInBits, channel, signed, bigEndian);
    }
    TargetDataLine audio_in;
    
    DatagramSocket serverSocket;
    byte[] receiveData;
    byte[] sendData;
    public int port = 8888;
    
    public SourceDataLine audio_out;
    /**
     * Creates new form FormCall
     */
    public FormCall(){
        initComponents();
    }
    String username;
    public FormCall(String uname){
            initComponents();
        try {
            username = uname;
            s = new Socket("localhost", 23144);
            inp = new BufferedReader(new InputStreamReader(s.getInputStream()));
            out = new DataOutputStream(s.getOutputStream());
            if (t == null) {
                t = new Thread(this, "Call-Admin-Side");
                t.start();
            }
        } catch (IOException ex) {
            Logger.getLogger(FormCall.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCall = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCall.setText("Call");
        btnCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCallActionPerformed(evt);
            }
        });

        jLabel1.setText("call admin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnCall))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnCall)
                .addGap(125, 125, 125))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCallActionPerformed
        // TODO add your handling code here:
        String call = btnCall.getText();
        
        if (call.equals("Call")) {
        jLabel1.setText("connecting");
            try {
                btnCall.setText("End");
                System.out.println("menelpon");
                out.writeBytes("[CALL]"+username+"\n");
                System.out.println("[CALL]"+username);
                System.out.println("menunggu jwbn");
                
                
            } catch (IOException ex) {
                Logger.getLogger(FormCall.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            try {
                btnCall.setText("Call");
                out.writeBytes("[END-CALL]\n");
                jLabel1.setText("Disconnect");
                calling = false;
            } catch (IOException ex) {
                Logger.getLogger(FormCall.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCall().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCall;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public void initAudio(){
        try {
            AudioFormat format = getAudioFormat();
            DataLine.Info info_out = new DataLine.Info(SourceDataLine.class, format);
            DataLine.Info info = new DataLine.Info(TargetDataLine.class, format);
            if (!AudioSystem.isLineSupported(info_out) && !AudioSystem.isLineSupported(info)) {
                System.out.println("not support");
                System.exit(0);
            }
            audio_in = (TargetDataLine) AudioSystem.getLine(info);
            audio_in.open();
            audio_in.start();
            recorder_thread r = new recorder_thread(this);
            InetAddress inet = InetAddress.getByName(add_server);
            r.audio_in = audio_in;
            r.dout = new DatagramSocket();
            r.server_ip = inet;
            r.server_port = port_server;
            calling =true;
            r.start();
            audio_out = (SourceDataLine) AudioSystem.getLine(info_out);
            audio_out.open(format);
            audio_out.start();
            player_thread_client p = new player_thread_client(this);
            p.din = new DatagramSocket(port);
            p.audio_out = audio_out;
            p.start();
        } catch (LineUnavailableException | UnknownHostException | SocketException ex) {
            Logger.getLogger(FormCall.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
  
    public void Status(String status)
    {
        if (status.contains("ACC")) {
            jLabel1.setText("connected");
            initAudio();
        }
        else{
            jLabel1.setText("admin tidak menjawab");
        }
    }
    @Override
    public void run() {
        while(true){
            try {
                String msg = inp.readLine();
                if (msg.contains("[END-CALL]")) {
                    btnCall.setText("Call");
                    jLabel1.setText("Disconnect");
                }
                else{
                    Status(msg);
                }
            } catch (IOException ex) {
                Logger.getLogger(FormCall.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
